#cloud-config
hostname: nginx
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEdhliHmCZHSeVGmIzcDtcNtDwsO+Q6SQEPycQYHkF8Q estibaliz.asir@hotmail.com
chpasswd:
  expire: False
  users:
    - name: debian
      password: asdasd
      type: text


